steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cana-vision-api/cana-vision-api:$COMMIT_SHA
      - .
images:
  - us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cana-vision-api/cana-vision-api:$COMMIT_SHA
